name: Run unittests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      WORKING_DIRECTORY: src
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install native deps
        run: sudo apt-get update && sudo apt-get install graphviz graphviz-dev
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies 
        run: python -m pip install -r requirements.txt
      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: python -m unittest -v

